[aws]
type = s3
provider = AWS
env_auth = true
region = us-east-2

[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AS3H6Ny4TNVrnGYqelSxp062xke_yZIM9EsS6GK8vjbNnVpHkxilKjLeZMWTfL_Tyl_UGyAyUtHJLoQiTqaqw6RqLVOZoK0Pce8UiTlm64ifg2jPPewVSQaVZpAkurQ7N22DG4DEstJvYM4AL8sM5t1Yivuv40etadRImoSLIinOxXeW2L1RvmQbeL5qNgmet62zDaYX5QaCgYKAZkSARcSFQHGX2MimyzH_GlcRLoDvwazdrsRqA0209","token_type":"Bearer","refresh_token":"1//052F4iJgkiqDgCgYIARAAGAUSNwF-L9Ir6UV039kTYSIp8fHbiBLfZzmK4SPOKis3wnku-GFTfmAFux3N_Wg5cYkYFA3rllU2-cg","expiry":"2025-09-12T06:19:25.677078109-04:00","expires_in":3599}
team_drive = 

