[aws]
type = s3
provider = AWS
env_auth = true
region = us-east-2

[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AS3H6Nzbomap1_vSiZ3tC4FbOQ9-cSHwGLaT2cEcdonMpo-Cy6Zkh6OqL0cLvr_nO22vZ2GVhXHUmDQxc_O2fimo5IfrV_KcgeVECKajcCFJf6dOG8dl0sWLwnlqdNTQCXAyulJ2AOlWErKpZhdL3Ede8R4yYnJqJpfMzfd2XzwaCgYKATASARcSFQHGX2Mi7Sq1UWIpJh2__YOMusufHg0178","token_type":"Bearer","refresh_token":"1//052F4iJgkiqDgCgYIARAAGAUSNwF-L9Ir6UV039kTYSIp8fHbiBLfZzmK4SPOKis3wnku-GFTfmAFux3N_Wg5cYkYFA3rllU2-cg","expiry":"2025-07-09T09:12:44.336816245-04:00"}
team_drive = 
