[aws]
type = s3
provider = AWS
env_auth = true
region = us-east-2

[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AS3H6NwRNxm4yD_KA1usJ2-8laNUzAhgwXIWiYs_t1AQviWdwHoXCGGZd52-Y0t_rx8O_56CExtozj2BnZq6A7vKDMRVXIC5kGDOo95jrhNa5qxUtIrBpoD-dSOKUCgRKhYWTz74GfDiFraZRywYFHIBtUVBUeBVGojirmGuXTrTn6NXFDeniELXb5roIWxNuaLlog7wngaCgYKAaYSARcSFQHGX2MinrCy1bwiBw-gV5QNtKWSXA0209","token_type":"Bearer","refresh_token":"1//052F4iJgkiqDgCgYIARAAGAUSNwF-L9Ir6UV039kTYSIp8fHbiBLfZzmK4SPOKis3wnku-GFTfmAFux3N_Wg5cYkYFA3rllU2-cg","expiry":"2025-09-12T05:19:25.689314302-04:00","expires_in":3599}
team_drive = 

